### ISSUE TITLE
delimited text parser needs to alert on errors

### ISSUE THREAD

**Issue by guidorice** [ncgr/cmap-js#21]
The papaparse library is being invoked like this in DataSourceModel:
```
this.parseResult = parser.parse(data, {
      header: true,
      dynamicTyping: true,
      skipEmptyLines: true
    });
```
However, for some data sources there are lots of errors being generated by the papaparse library, but not displayed or reported, such as tons of these:

> {"type":"FieldMismatch","code":"TooFewFields","message":"Too few fields: expected 9 fields but parsed 7","row":29659}

**Comment by adf-ncgr** [comment]
@guidorice : agreed that we should get some error reporting for parse failures; wondering which of the files is malformed, though? (wasn't expecting to have field count problems, though it's certainly possible- another possibility might be that papaparse is handling empty fields differently than some of the other tools that have worked on these files)

**Comment by guidorice** [comment]
Error handling still needs some improvement, e.g. 404 not found is a bit messy, and errors should get a better display (like a mithril component). However I fixed the issue with the data file, and added an alert.

https://github.com/ncgr/cmap-js/commit/882c46f5bd39fa5638cd6db486ca1284c56f4d5d
https://github.com/ncgr/cmap-js/commit/12023de3adbec5d80e8b85c00fa353c1355cdd80
