### ISSUE TITLE
Unable to scroll when zoomed in.

### ISSUE THREAD

**Issue by ekcannon** [ncgr/cmap-js#32]
It isn't possible to scroll when zoomed in. I wanted to see the names of the markers that were in that region that appeared to be misassembled but couldn't find any way to zoom in at the bottom of the left backbone.

**Comment by awilkey** [comment]
Fixed with #34 , now clicking on ruler allows you to scroll. click-and-drag outside the ruler but still within the canvas allows for selecting a zoom as a "box zoom", though drawing the actual box is still pending.
